'use client';

import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

const widgets: Record<string, ComponentType> = {
  'word-counter': dynamic(() => import('./widgets/word-counter').then((m) => ({ default: m.default })), { ssr: false }),
  'character-counter': dynamic(() => import('./widgets/character-counter').then((m) => ({ default: m.default })), { ssr: false }),
  'case-converter': dynamic(() => import('./widgets/case-converter').then((m) => ({ default: m.default })), { ssr: false }),
  'lorem-ipsum': dynamic(() => import('./widgets/lorem-ipsum').then((m) => ({ default: m.default })), { ssr: false }),
  'text-to-slug': dynamic(() => import('./widgets/text-to-slug').then((m) => ({ default: m.default })), { ssr: false }),
  'remove-duplicate-lines': dynamic(() => import('./widgets/remove-duplicate-lines').then((m) => ({ default: m.default })), { ssr: false }),
  'password-generator': dynamic(() => import('./widgets/password-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'password-strength-checker': dynamic(() => import('./widgets/password-strength-checker').then((m) => ({ default: m.default })), { ssr: false }),
  'hash-generator': dynamic(() => import('./widgets/hash-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'base64-encoder': dynamic(() => import('./widgets/base64-encoder').then((m) => ({ default: m.default })), { ssr: false }),
  'json-formatter': dynamic(() => import('./widgets/json-formatter').then((m) => ({ default: m.default })), { ssr: false }),
  'css-minifier': dynamic(() => import('./widgets/css-minifier').then((m) => ({ default: m.default })), { ssr: false }),
  'js-minifier': dynamic(() => import('./widgets/js-minifier').then((m) => ({ default: m.default })), { ssr: false }),
  'html-formatter': dynamic(() => import('./widgets/html-formatter').then((m) => ({ default: m.default })), { ssr: false }),
  'color-picker': dynamic(() => import('./widgets/color-picker').then((m) => ({ default: m.default })), { ssr: false }),
  'regex-tester': dynamic(() => import('./widgets/regex-tester').then((m) => ({ default: m.default })), { ssr: false }),
  'url-encoder': dynamic(() => import('./widgets/url-encoder').then((m) => ({ default: m.default })), { ssr: false }),
  'meta-tag-generator': dynamic(() => import('./widgets/meta-tag-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'markdown-preview': dynamic(() => import('./widgets/markdown-preview').then((m) => ({ default: m.default })), { ssr: false }),
  'age-calculator': dynamic(() => import('./widgets/age-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'bmi-calculator': dynamic(() => import('./widgets/bmi-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'percentage-calculator': dynamic(() => import('./widgets/percentage-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'tip-calculator': dynamic(() => import('./widgets/tip-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'currency-converter': dynamic(() => import('./widgets/currency-converter').then((m) => ({ default: m.default })), { ssr: false }),
  'unit-converter': dynamic(() => import('./widgets/unit-converter').then((m) => ({ default: m.default })), { ssr: false }),
  'qr-code-generator': dynamic(() => import('./widgets/qr-code-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'keyword-density': dynamic(() => import('./widgets/keyword-density').then((m) => ({ default: m.default })), { ssr: false }),
  'meta-description-generator': dynamic(() => import('./widgets/meta-description-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'privacy-policy-generator': dynamic(() => import('./widgets/privacy-policy-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'sitemap-generator': dynamic(() => import('./widgets/sitemap-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'image-compressor': dynamic(() => import('./widgets/image-compressor').then((m) => ({ default: m.default })), { ssr: false }),
  'image-resizer': dynamic(() => import('./widgets/image-resizer').then((m) => ({ default: m.default })), { ssr: false }),
  'image-converter': dynamic(() => import('./widgets/image-converter').then((m) => ({ default: m.default })), { ssr: false }),
  'background-remover': dynamic(() => import('./widgets/background-remover').then((m) => ({ default: m.default })), { ssr: false }),
  'favicon-generator': dynamic(() => import('./widgets/favicon-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'pdf-compressor': dynamic(() => import('./widgets/pdf-compressor').then((m) => ({ default: m.default })), { ssr: false }),
  'merge-pdf': dynamic(() => import('./widgets/merge-pdf').then((m) => ({ default: m.default })), { ssr: false }),
  'pdf-to-jpg': dynamic(() => import('./widgets/pdf-to-jpg').then((m) => ({ default: m.default })), { ssr: false }),
  'split-pdf': dynamic(() => import('./widgets/split-pdf').then((m) => ({ default: m.default })), { ssr: false }),
  'word-to-pdf': dynamic(() => import('./widgets/word-to-pdf').then((m) => ({ default: m.default })), { ssr: false }),
  // New 100 tools — all functional
  'tiktok-downloader': dynamic(() => import('./widgets/tiktok-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'youtube-downloader': dynamic(() => import('./widgets/youtube-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'instagram-downloader': dynamic(() => import('./widgets/instagram-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'facebook-video-downloader': dynamic(() => import('./widgets/facebook-video-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'twitter-video-downloader': dynamic(() => import('./widgets/twitter-video-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'youtube-to-mp3': dynamic(() => import('./widgets/youtube-to-mp3').then((m) => ({ default: m.default })), { ssr: false }),
  'pinterest-downloader': dynamic(() => import('./widgets/pinterest-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'vimeo-downloader': dynamic(() => import('./widgets/vimeo-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'youtube-thumbnail-downloader': dynamic(() => import('./widgets/youtube-thumbnail-downloader').then((m) => ({ default: m.default })), { ssr: false }),
  'video-to-gif': dynamic(() => import('./widgets/video-to-gif').then((m) => ({ default: m.default })), { ssr: false }),
  'audio-trimmer': dynamic(() => import('./widgets/audio-trimmer').then((m) => ({ default: m.default })), { ssr: false }),
  'spotify-to-mp3': dynamic(() => import('./widgets/spotify-to-mp3').then((m) => ({ default: m.default })), { ssr: false }),
  'hashtag-generator': dynamic(() => import('./widgets/hashtag-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'instagram-bio-generator': dynamic(() => import('./widgets/instagram-bio-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'instagram-fonts': dynamic(() => import('./widgets/instagram-fonts').then((m) => ({ default: m.default })), { ssr: false }),
  'youtube-banner-maker': dynamic(() => import('./widgets/youtube-banner-maker').then((m) => ({ default: m.default })), { ssr: false }),
  'engagement-rate-calculator': dynamic(() => import('./widgets/engagement-rate-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'email-subject-generator': dynamic(() => import('./widgets/email-subject-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'tiktok-bio-generator': dynamic(() => import('./widgets/tiktok-bio-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'social-media-calendar': dynamic(() => import('./widgets/social-media-calendar').then((m) => ({ default: m.default })), { ssr: false }),
  'link-in-bio-generator': dynamic(() => import('./widgets/link-in-bio-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'invoice-generator': dynamic(() => import('./widgets/invoice-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'loan-calculator': dynamic(() => import('./widgets/loan-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'mortgage-calculator': dynamic(() => import('./widgets/mortgage-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'compound-interest': dynamic(() => import('./widgets/compound-interest').then((m) => ({ default: m.default })), { ssr: false }),
  'vat-calculator': dynamic(() => import('./widgets/vat-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'discount-calculator': dynamic(() => import('./widgets/discount-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'profit-margin-calculator': dynamic(() => import('./widgets/profit-margin-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'salary-calculator': dynamic(() => import('./widgets/salary-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'roi-calculator': dynamic(() => import('./widgets/roi-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'receipt-generator': dynamic(() => import('./widgets/receipt-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'pay-stub-generator': dynamic(() => import('./widgets/pay-stub-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'hours-calculator': dynamic(() => import('./widgets/hours-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-blog-generator': dynamic(() => import('./widgets/ai-blog-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-email-writer': dynamic(() => import('./widgets/ai-email-writer').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-paraphraser': dynamic(() => import('./widgets/ai-paraphraser').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-summarizer': dynamic(() => import('./widgets/ai-summarizer').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-grammar-checker': dynamic(() => import('./widgets/ai-grammar-checker').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-ad-copy': dynamic(() => import('./widgets/ai-ad-copy').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-business-name': dynamic(() => import('./widgets/ai-business-name').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-caption-generator': dynamic(() => import('./widgets/ai-caption-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-cover-letter': dynamic(() => import('./widgets/ai-cover-letter').then((m) => ({ default: m.default })), { ssr: false }),
  'ai-plagiarism-checker': dynamic(() => import('./widgets/ai-plagiarism-checker').then((m) => ({ default: m.default })), { ssr: false }),
  'resume-builder': dynamic(() => import('./widgets/resume-builder').then((m) => ({ default: m.default })), { ssr: false }),
  'text-repeater': dynamic(() => import('./widgets/text-repeater').then((m) => ({ default: m.default })), { ssr: false }),
  'text-reverser': dynamic(() => import('./widgets/text-reverser').then((m) => ({ default: m.default })), { ssr: false }),
  'online-notepad': dynamic(() => import('./widgets/online-notepad').then((m) => ({ default: m.default })), { ssr: false }),
  'signature-generator': dynamic(() => import('./widgets/signature-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'random-word-generator': dynamic(() => import('./widgets/random-word-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'title-case-converter': dynamic(() => import('./widgets/title-case-converter').then((m) => ({ default: m.default })), { ssr: false }),
  'cover-letter-generator': dynamic(() => import('./widgets/cover-letter-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'reading-time-calculator': dynamic(() => import('./widgets/reading-time-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'table-of-contents': dynamic(() => import('./widgets/table-of-contents').then((m) => ({ default: m.default })), { ssr: false }),
  'meme-generator': dynamic(() => import('./widgets/meme-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'image-cropper': dynamic(() => import('./widgets/image-cropper').then((m) => ({ default: m.default })), { ssr: false }),
  'image-color-picker': dynamic(() => import('./widgets/image-color-picker').then((m) => ({ default: m.default })), { ssr: false }),
  'image-rotator': dynamic(() => import('./widgets/image-rotator').then((m) => ({ default: m.default })), { ssr: false }),
  'watermark-adder': dynamic(() => import('./widgets/watermark-adder').then((m) => ({ default: m.default })), { ssr: false }),
  'photo-enhancer': dynamic(() => import('./widgets/photo-enhancer').then((m) => ({ default: m.default })), { ssr: false }),
  'image-filters': dynamic(() => import('./widgets/image-filters').then((m) => ({ default: m.default })), { ssr: false }),
  'image-to-base64': dynamic(() => import('./widgets/image-to-base64').then((m) => ({ default: m.default })), { ssr: false }),
  'image-metadata': dynamic(() => import('./widgets/image-metadata').then((m) => ({ default: m.default })), { ssr: false }),
  'aspect-ratio-calculator': dynamic(() => import('./widgets/aspect-ratio-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'css-gradient-generator': dynamic(() => import('./widgets/css-gradient-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'css-box-shadow': dynamic(() => import('./widgets/css-box-shadow').then((m) => ({ default: m.default })), { ssr: false }),
  'ip-lookup': dynamic(() => import('./widgets/ip-lookup').then((m) => ({ default: m.default })), { ssr: false }),
  'dns-lookup': dynamic(() => import('./widgets/dns-lookup').then((m) => ({ default: m.default })), { ssr: false }),
  'unix-timestamp': dynamic(() => import('./widgets/unix-timestamp').then((m) => ({ default: m.default })), { ssr: false }),
  'uuid-generator': dynamic(() => import('./widgets/uuid-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'json-to-csv': dynamic(() => import('./widgets/json-to-csv').then((m) => ({ default: m.default })), { ssr: false }),
  'http-status-checker': dynamic(() => import('./widgets/http-status-checker').then((m) => ({ default: m.default })), { ssr: false }),
  'jwt-decoder': dynamic(() => import('./widgets/jwt-decoder').then((m) => ({ default: m.default })), { ssr: false }),
  'port-scanner': dynamic(() => import('./widgets/port-scanner').then((m) => ({ default: m.default })), { ssr: false }),
  'calorie-calculator': dynamic(() => import('./widgets/calorie-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'water-intake-calculator': dynamic(() => import('./widgets/water-intake-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'ideal-weight': dynamic(() => import('./widgets/ideal-weight').then((m) => ({ default: m.default })), { ssr: false }),
  'sleep-calculator': dynamic(() => import('./widgets/sleep-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'protein-calculator': dynamic(() => import('./widgets/protein-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'ovulation-calculator': dynamic(() => import('./widgets/ovulation-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'due-date-calculator': dynamic(() => import('./widgets/due-date-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'pace-calculator': dynamic(() => import('./widgets/pace-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'timezone-converter': dynamic(() => import('./widgets/timezone-converter').then((m) => ({ default: m.default })), { ssr: false }),
  'date-difference': dynamic(() => import('./widgets/date-difference').then((m) => ({ default: m.default })), { ssr: false }),
  'random-number': dynamic(() => import('./widgets/random-number').then((m) => ({ default: m.default })), { ssr: false }),
  'random-name-picker': dynamic(() => import('./widgets/random-name-picker').then((m) => ({ default: m.default })), { ssr: false }),
  'pomodoro-timer': dynamic(() => import('./widgets/pomodoro-timer').then((m) => ({ default: m.default })), { ssr: false }),
  'stopwatch': dynamic(() => import('./widgets/stopwatch').then((m) => ({ default: m.default })), { ssr: false }),
  'url-shortener': dynamic(() => import('./widgets/url-shortener').then((m) => ({ default: m.default })), { ssr: false }),
  'checklist-maker': dynamic(() => import('./widgets/checklist-maker').then((m) => ({ default: m.default })), { ssr: false }),
  'meeting-cost-calculator': dynamic(() => import('./widgets/meeting-cost-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'domain-age-checker': dynamic(() => import('./widgets/domain-age-checker').then((m) => ({ default: m.default })), { ssr: false }),
  'gpa-calculator': dynamic(() => import('./widgets/gpa-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'grade-calculator': dynamic(() => import('./widgets/grade-calculator').then((m) => ({ default: m.default })), { ssr: false }),
  'citation-generator': dynamic(() => import('./widgets/citation-generator').then((m) => ({ default: m.default })), { ssr: false }),
  'roman-numerals': dynamic(() => import('./widgets/roman-numerals').then((m) => ({ default: m.default })), { ssr: false }),
  'number-base-converter': dynamic(() => import('./widgets/number-base-converter').then((m) => ({ default: m.default })), { ssr: false }),
  'flashcard-maker': dynamic(() => import('./widgets/flashcard-maker').then((m) => ({ default: m.default })), { ssr: false }),
  'pronunciation-guide': dynamic(() => import('./widgets/pronunciation-guide').then((m) => ({ default: m.default })), { ssr: false }),
  'logic-puzzle-generator': dynamic(() => import('./widgets/logic-puzzle-generator').then((m) => ({ default: m.default })), { ssr: false }),
};

export function ToolWidgetLoader({ slug }: { slug: string }) {
  const Widget = widgets[slug];
  if (!Widget) {
    return (
      <div className="rounded-xl border border-amber-200 bg-amber-50 p-6 text-amber-900">
        <p className="font-semibold">This tool is being updated.</p>
        <p className="text-sm mt-1">Please try again later or browse other tools.</p>
      </div>
    );
  }
  return <Widget />;
}
