/**
 * Long-form local context for each country landing page.
 *
 * The country pages were ~68% identical to each other by 8-word sequence,
 * which is the doorway-page pattern Google's spam policy names and a likely
 * contributor to the AdSense "low value content" review. The fix is not more
 * pages — it is a larger genuinely-local share of each existing page.
 *
 * Every paragraph here has to answer something a family in *that* country
 * would ask and a family elsewhere would not. Claims about tutor languages
 * stay consistent with `communityLanguages` in quranAcademyCountries.ts;
 * nothing here asserts a capability the academy has not already stated.
 */

export const COUNTRY_LOCAL_CONTEXT: Record<string, string[]> = {
  uk: [
    'Britain has the most established madrasah network in Western Europe. Most towns with a Muslim population of any size have a mosque running after-school classes five evenings a week, and for a lot of families the question is not whether their child can learn Quran locally but whether the local class is working. A group of twenty to thirty children with one teacher means a child might read aloud for ninety seconds in an hour, and weak letters go uncorrected for months because nobody has time to hear them properly.',
    'The scheduling pressure is specific too. A 3:15pm school finish leaves a usable window before dinner, but it collapses in secondary school once homework and GCSE coursework arrive, and Isha drifts past 10:30pm in June — far too late for a primary-age child on a school night. Families typically end up splitting the year: weekday late afternoons through winter, weekend mornings in summer when the evenings become unusable.',
    'Language continuity matters more in Britain than most places because of how the generations split. Many children are monolingual English speakers while their grandparents are more comfortable in Urdu, Bengali or Gujarati, and the local madrasah may teach in a language the child follows only partially. Tutors who can work in English while still being understood by the rest of the household let the whole family stay involved in what the child is learning.',
  ],
  ireland: [
    'Ireland is a very different situation from Britain despite the proximity. The Muslim community here is small, recent and concentrated — Dublin has real infrastructure around the Islamic Cultural Centre in Clonskeagh and the mosque on South Circular Road, and Cork and Galway have growing communities, but a family in a smaller town often has no weekly Quran class within a reasonable drive at all. The problem is not class size. It is that there is frequently nothing local to join.',
    'That changes what an online class is for. In Britain it usually supplements a madrasah; in much of Ireland it is the entire provision, which means consistency matters more. A child who misses a fortnight has no parallel class picking up the slack, so the schedule needs to be one the family can actually sustain through the school year rather than an ambitious one abandoned by November.',
    'Timing is straightforward — Ireland keeps the same clock as the UK, so late-afternoon and early-evening weekday slots work, with the same summer problem when Isha moves very late. Tutors working in English and Arabic cover most households here, since the community is more mixed in origin than Britain\'s and English is more consistently the shared family language.',
  ],
  germany: [
    'Germany\'s Muslim population is largely descended from Turkish families who arrived from the 1960s onward, and the religious infrastructure reflects that: mosque associations like DITIB and the Milli Görüş network run Quran courses that are often taught partly in Turkish. That works well for families who kept the language and much less well for the third and fourth generation, whose German is native and whose Turkish may be conversational at best. A child can end up learning Quran through a language they are not fully fluent in, which slows everything down.',
    'The school day helps here in a way it does not elsewhere. Many Grundschulen still finish around lunchtime or in the early afternoon, and while Ganztagsschule provision has expanded considerably, a large number of German children have genuinely free afternoons. That opens up slots that a British or Spanish family simply does not have, and it means lessons can happen when a child is still alert rather than at the end of a long day.',
    'For German families the practical question is usually continuity with what the child already does at the mosque. Our tutors work in English and Arabic, with Turkish-friendly tutors available, so a family can either carry on with the syllabus their Moschee uses or switch to a structured one-to-one track — but it is worth deciding which before starting, rather than having the child work through two different methods at once.',
  ],
  france: [
    'France has the largest Muslim population in Western Europe, predominantly of Algerian, Moroccan and Tunisian background, and it also has the strictest separation of religion from state schooling. Laïcité means there is no religious instruction in the public system at all, so everything a child learns about Quran happens outside school hours through the mosque, an association, or the family. That places the whole burden on evenings and weekends in a way that is not true in countries with faith schools.',
    'The traditional free Wednesday is the scheduling feature worth knowing about. Many French primary schools still keep Wednesday afternoons clear — the pattern has varied by commune since the rhythmes scolaires reforms — and where it survives it is by far the easiest slot in the week for a sustained lesson, because the child is not fitting it around a full school day. Families who have it should use it before reaching for weekday evenings.',
    'Most Maghrebi families in France have some Arabic in the household, often darija rather than classical, which helps with pronunciation instincts but does not automatically transfer to reading fuṣḥā. Tutors working in Arabic alongside English, including Maghrebi Arabic-friendly tutors, can meet a child where their ear already is, while still teaching the classical reading properly rather than letting dialect habits settle into the recitation.',
  ],
  netherlands: [
    'Dutch Muslim communities are mainly Turkish and Moroccan-Berber in origin, and the two have quite different religious-education habits — Turkish mosque associations tend to run more formal weekly courses, while many Moroccan families have historically taught at home or relied on a smaller local circle. Between them there is decent provision in Amsterdam, Rotterdam, The Hague and Utrecht, and noticeably less outside the Randstad.',
    'Dutch school days end early by European standards, and the free Wednesday afternoon is still common in primary education, which gives families genuinely usable daytime slots. That is worth taking advantage of, because Dutch evenings fill up quickly with sport and the Netherlands has one of the highest rates of organised children\'s activity in Europe — a Quran lesson competing with football training on a Tuesday evening usually loses.',
    'The language question here is layered. Many Moroccan-Dutch children hear Tarifit or another Berber variety at home rather than Arabic, so Arabic is genuinely a new language rather than a familiar one, and assuming otherwise sets the pace wrong from the first lesson. We have Berber-friendly and Turkish-friendly tutors alongside English and Arabic, which mostly matters for keeping parents in the loop rather than for teaching the child.',
  ],
  belgium: [
    'Belgium\'s Muslim community is concentrated in Brussels, Antwerp, Charleroi and Liège, and is mainly Moroccan and Turkish in origin. What makes Belgium different from its neighbours is the language split: a family in Brussels or Wallonia lives in French, a family in Flanders in Dutch, and religious provision tends to organise along the same lines. Unlike France, Belgium does fund religious instruction within the school system, including Islamic religious education in many state schools — but its quality and content vary considerably between schools and it rarely covers recitation at any depth.',
    'That leaves a specific gap. A Belgian child may well be getting some Islamic studies at school while receiving no structured tajweed or reading practice at all, so families often arrive looking for exactly the technical piece the school cannot provide rather than for general religious education. Starting with an honest assessment of what the child can actually read, rather than assuming school coverage translates into fluency, avoids a lot of wasted time.',
    'Belgian school days run to mid or late afternoon, with Wednesday afternoons free in much of the system — again the best slot in the week. Our tutors work in English and Arabic, with Maghrebi Arabic-friendly and Turkish-friendly tutors available, which matters most for the parent conversation rather than the lesson itself.',
  ],
  spain: [
    'Spain\'s Muslim population is largely Moroccan in origin, with the biggest communities in Catalonia, Madrid, Andalusia and Murcia. Provision is patchy: Barcelona and Madrid have established mosques running classes, but in smaller towns and agricultural areas — where a lot of Moroccan families actually live — organised Quran teaching can be limited to an informal circle or nothing at all.',
    'The Spanish daily rhythm is the real scheduling difference and it catches out anyone applying a northern European template. The school day frequently runs until around 5pm with a long midday break, dinner is commonly at 9pm or later, and children stay up correspondingly later. An early-evening slot that suits a British family lands in the middle of the Spanish afternoon; the workable windows here are usually later in the evening than families elsewhere would consider reasonable for a child.',
    'Most Moroccan-Spanish children speak Spanish natively, often Catalan too, with darija at home and limited classical Arabic. Tutors working in Arabic including Maghrebi Arabic-friendly tutors can bridge the household, but the teaching itself is best done in a language the child is fully fluent in — which for a child born in Spain usually means English or Arabic taught patiently from the beginning rather than assumed.',
  ],
  italy: [
    'Italy has a sizeable Muslim population — Moroccan, Bangladeshi, Pakistani, Egyptian, Albanian and Senegalese communities among others — but comparatively little formal religious infrastructure. Italy has relatively few purpose-built mosques for its population size, and a great deal of communal prayer happens in converted spaces, cultural association rooms and prayer halls rather than in buildings with room for a weekly children\'s class. Provision therefore depends heavily on which city you are in: Milan, Brescia and Rome have options, many places have very little.',
    'That absence of a default local class is the main reason Italian families look online, and it changes the expectation. Rather than supplementing a madrasah, the lesson is generally the child\'s only structured contact with Quran reading, so progress depends entirely on whether the weekly rhythm holds. Italian school schedules vary — some schools run six shorter mornings including Saturday, others a five-day week finishing mid-afternoon — so it is worth building the slot around your actual school calendar rather than a standard weekday-evening assumption.',
    'Because the community is unusually mixed in origin, there is no single household language to design around. Our tutors work in English, Arabic, Urdu and Bengali, which covers most Italian Muslim families, though the child themselves will almost always be most comfortable in Italian and then English.',
  ],
  sweden: [
    'Sweden\'s Muslim communities are largely Somali, Syrian, Iraqi and Bosnian in origin, shaped more by recent refugee migration than by the older labour migration that shaped Germany or Britain. That means many families are still establishing routines that elsewhere are generations old, and religious education provision varies enormously between Stockholm, Gothenburg and Malmö and the smaller towns where many families were originally placed.',
    'The latitude creates a genuine scheduling problem that families further south never face. In June, twilight in much of Sweden never fully ends, so Isha either falls extremely late or does not occur by the standard astronomical definition at all, and communities rely on calculated methods to fix a time. Practically, that means any lesson schedule anchored to Isha falls apart for part of the year. Anchoring to the clock and to the school day instead — and accepting that the timetable will shift between the dark winter and the light summer — is the approach that actually survives a full year.',
    'Swedish schools finish early and Swedish children generally have more unstructured afternoon time than their British or Spanish counterparts, which makes the practical slots easier once you stop trying to tie them to prayer times. Our tutors work in English and Arabic with Somali-friendly and Urdu-speaking tutors available, which matters particularly for Somali-Swedish households where the parents\' Arabic may be limited.',
  ],
  norway: [
    'Norway\'s largest Muslim community is Pakistani in origin, concentrated heavily in Oslo, with significant Somali, Iraqi and Syrian populations alongside. Oslo has well-established mosques running weekend classes; outside the capital, and particularly along the west coast and in the north, families are often the only Muslim household for some distance and have no local option whatsoever.',
    'Norway sits far enough north that the daylight problem is more extreme than Sweden\'s. Above the Arctic Circle the sun does not set at all for weeks in summer, and in the far north it does not properly rise for weeks in winter. Prayer times in those conditions are determined by calculation rather than observation, and any attempt to schedule a child\'s weekly lesson around them will not hold. A fixed clock time, reviewed twice a year, is the only thing that works — and the darkness itself is worth planning around, because a 4pm lesson in December happens in what feels like the middle of the night.',
    'For Norwegian-Pakistani families, the language split will be familiar: children fluent in Norwegian, parents and grandparents more comfortable in Urdu or Punjabi. Tutors working in English and Urdu, with Arabic and Somali-friendly tutors available, let the lesson run in the child\'s strongest language while the rest of the household can still follow what is being covered.',
  ],
  denmark: [
    'Denmark\'s Muslim population is mainly Turkish, Iraqi, Somali, Pakistani and Lebanese in origin, concentrated in Copenhagen, Aarhus and Odense. Provision exists in the cities and thins out quickly beyond them. Denmark also has a notably sharp public debate about Islamic education, which some families find makes them more deliberate about what their children are taught and by whom — a private one-to-one lesson is partly a response to wanting visibility into the actual content.',
    'The daylight swing is less severe than Norway\'s but still substantial enough to matter. Copenhagen summers run to very late twilight and winter afternoons are dark by mid-afternoon, so the same principle applies: fix the lesson to the clock and the school day, review it when the seasons turn, and do not build the routine around a prayer time that moves by hours across the year.',
    'Danish school days are relatively short and Danish children have comparatively protected family time in the late afternoon and evening, which makes a consistent weekly slot easier to hold than in countries with heavier homework loads. Our tutors work in English, Arabic and Urdu with Turkish-friendly tutors available, covering most Danish Muslim households.',
  ],
  usa: [
    'The dominant model for children\'s Islamic education in America is the weekend school — Sunday classes at the masjid, occasionally Saturday, covering Quran alongside Islamic studies in a group setting. It is a genuinely valuable institution socially, connecting children to a community they may not otherwise see during the week. It is also, structurally, a group class held once a week, which means recitation gets a few minutes per child and correction happens slowly if at all.',
    'Geography is the practical complication that is unique to the United States. The contiguous states span four time zones, so a slot that suits a family in New Jersey is three hours out for one in California, and a lesson that works after school on the East Coast lands in the early afternoon out West. Anyone comparing schedules with relatives in another state should be explicit about which zone they are quoting — it is the single most common source of missed first lessons.',
    'American Muslim families are more diverse in origin than almost anywhere else, spanning South Asian, Arab, African American, West African and convert households with no shared heritage language. In practice that means English is the language the child is fluent in and the language the lesson should run in, with Arabic taught from first principles rather than assumed. Our tutors work in English, Arabic, Urdu and Bengali, which covers the parent conversation for most households.',
  ],
  canada: [
    'Canadian Muslim communities are concentrated in the Greater Toronto Area, Montreal, Vancouver, Calgary and Ottawa, with a large South Asian population in the GTA and a significant Arab and North African presence in Montreal. Weekend Islamic schools follow much the same pattern as in the United States, and face the same constraint: a good community experience, with limited individual recitation time.',
    'Canada\'s span is even wider than America\'s — six time zones, plus Newfoundland\'s half-hour offset — so the scheduling caution applies with more force, particularly for families coordinating with relatives elsewhere in the country. The northern winter is the other factor worth planning around: in much of Canada it is fully dark well before dinner from November through February, and a late-afternoon lesson in Edmonton in December feels very different from the same slot in June.',
    'Montreal adds a wrinkle the rest of the country does not have, since many Muslim families there operate primarily in French and children are schooled in French under Quebec\'s language rules. Our tutors work in English, Arabic, Urdu and Bengali with Somali-friendly tutors available; for a Francophone household the lesson itself generally runs in English or Arabic, which is worth confirming suits the child before booking.',
  ],
  australia: [
    'Australia\'s Muslim community is long-established — Lebanese and Turkish families have been in Sydney and Melbourne for generations, alongside more recent Afghan, Iraqi, Bangladeshi and Somali arrivals. Both cities have substantial Islamic schools and mosque programmes. Perth, Adelaide, Brisbane and regional areas have considerably less, and for families outside the two big cities an online lesson is frequently the only structured option.',
    'The time zone is the thing that makes Australia genuinely different, and it works in families\' favour more than they expect. Because Australian clocks run well ahead of South Asia and the Middle East, an Australian after-school or early-evening slot falls during the tutor\'s ordinary working day rather than at an awkward hour, which tends to mean better availability and more consistent teachers than families assume when they first enquire. The reverse is also true: an Australian morning slot lands in the middle of the night for the tutor and is the one thing that genuinely cannot be arranged.',
    'The school calendar is the other Australian specific. The academic year runs from late January to December, with the long break over Christmas and January and shorter breaks between four terms — so the natural point to start or restart is the opposite end of the year from the northern hemisphere, and the summer holiday that disrupts everyone else\'s schedule in July is mid-term here. Our tutors work in English, Arabic and Urdu with Turkish-friendly tutors available.',
  ],
};
