export type Tool = {
  id: string;
  name: string;
  category: string;
  categoryLabel: string;
  emoji: string;
  tagline: string;
  description: string;
  longDescription: string;
  url: string;
  tags: string[];
  isFree: boolean;
  hasPaid: boolean;
};

export const tools: Tool[] = [
  {
    id: 'canva',
    name: 'Canva',
    category: 'design',
    categoryLabel: 'Design',
    emoji: '🎨',
    tagline: 'Design anything in minutes',
    description: 'Drag-and-drop design for social posts, presentations, logos, and more.',
    longDescription: "Canva is the world's most popular graphic design platform used by over 135 million people. Create social media graphics, presentations, posters, videos, and more with thousands of free templates. No design experience needed.",
    url: 'https://canva.com',
    tags: ['graphic design', 'social media', 'presentations', 'templates', 'logo'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'design',
    categoryLabel: 'Design',
    emoji: '🖌️',
    tagline: 'Professional UI/UX design in the browser',
    description: 'Professional UI/UX design and prototyping tool used by every designer.',
    longDescription: "Figma is the industry-standard collaborative design tool for UI/UX designers. Create wireframes, prototypes, design systems, and handoff specs all in one browser-based tool. Free for up to 3 projects.",
    url: 'https://figma.com',
    tags: ['UI design', 'UX design', 'prototyping', 'wireframes', 'collaboration'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'coolors',
    name: 'Coolors',
    category: 'design',
    categoryLabel: 'Design',
    emoji: '🎨',
    tagline: 'Beautiful color palettes in one click',
    description: 'Generate beautiful color palettes instantly. Essential for branding and design.',
    longDescription: 'Coolors is the fastest color palette generator on the web. Hit the spacebar to generate new palettes, lock colors you love, and export in any format. Used by designers worldwide for branding and web projects.',
    url: 'https://coolors.co',
    tags: ['color palette', 'branding', 'color scheme', 'design tool'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'google-fonts',
    name: 'Google Fonts',
    category: 'design',
    categoryLabel: 'Design',
    emoji: '🔤',
    tagline: '1,500+ free fonts for any project',
    description: '1,500+ free fonts for any web or print project — completely free, no license worries.',
    longDescription: 'Google Fonts offers over 1,500 open-source fonts you can use in any project — commercial or personal — with no attribution required. Filter by style, thickness, and language. Integrate directly via CSS or download.',
    url: 'https://fonts.google.com',
    tags: ['fonts', 'typography', 'web fonts', 'free fonts'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'flaticon',
    name: 'Flaticon',
    category: 'design',
    categoryLabel: 'Design',
    emoji: '✨',
    tagline: 'Millions of free icons',
    description: 'Millions of free icons in SVG, PNG, and icon font formats.',
    longDescription: "Flaticon hosts the world's largest database of free icons — over 16 million icons across thousands of style packs. Download as SVG, PNG, or use as a web font. Essential for UI design and web projects.",
    url: 'https://flaticon.com',
    tags: ['icons', 'SVG', 'icon pack', 'UI icons', 'free icons'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'undraw',
    name: 'Undraw',
    category: 'design',
    categoryLabel: 'Design',
    emoji: '🖼️',
    tagline: 'Free open-source SVG illustrations',
    description: 'Free open-source SVG illustrations for any project with customizable colors.',
    longDescription: 'Undraw offers hundreds of beautiful, customizable SVG illustrations completely free. Change the primary color to match your brand and download. Perfect for landing pages, presentations, and app UI.',
    url: 'https://undraw.co',
    tags: ['illustrations', 'SVG', 'free illustrations', 'landing page', 'startup'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'grammarly',
    name: 'Grammarly',
    category: 'writing',
    categoryLabel: 'Writing',
    emoji: '✍️',
    tagline: 'AI grammar checker for everything you write',
    description: 'AI grammar and spell checker that works inside Gmail, Docs, and your browser.',
    longDescription: 'Grammarly is the most widely used writing assistant in the world. It checks grammar, spelling, tone, and clarity in real time across your browser, Gmail, Google Docs, Microsoft Office, and more. Free version covers essentials.',
    url: 'https://grammarly.com',
    tags: ['grammar', 'writing', 'spell check', 'AI writing', 'proofreading'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    category: 'writing',
    categoryLabel: 'Writing',
    emoji: '🪶',
    tagline: 'Paraphrase and rewrite any text with AI',
    description: 'Paraphrase, summarize, and rewrite text. Beloved by students and content writers.',
    longDescription: 'QuillBot uses AI to paraphrase, summarize, grammar-check, and translate text. With 7 rewriting modes, it helps you reword sentences while preserving meaning. Over 35 million users rely on it daily.',
    url: 'https://quillbot.com',
    tags: ['paraphrase', 'rewrite', 'summarize', 'AI writing', 'content'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'hemingway',
    name: 'Hemingway Editor',
    category: 'writing',
    categoryLabel: 'Writing',
    emoji: '📝',
    tagline: 'Write bold, clear, mistake-free prose',
    description: 'Highlights complex sentences and passive voice to make your writing clearer.',
    longDescription: 'The Hemingway Editor scores your writing for readability and highlights problem areas in different colors: complex sentences in yellow, very complex ones in red, passive voice in green. Helps you write at Grade 6–8 reading level for maximum clarity.',
    url: 'https://hemingwayapp.com',
    tags: ['readability', 'writing clarity', 'editing', 'passive voice', 'content'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'wordcounter',
    name: 'WordCounter',
    category: 'writing',
    categoryLabel: 'Writing',
    emoji: '🔢',
    tagline: 'Count words, characters, and reading time',
    description: 'Count words, characters, sentences, paragraphs, and reading time instantly.',
    longDescription: 'WordCounter is a simple but indispensable free tool that counts words, characters, sentences, paragraphs, and estimates reading time. Essential for blog writers, copywriters, and anyone working with content limits.',
    url: 'https://wordcounter.net',
    tags: ['word count', 'character count', 'writing tool', 'SEO', 'content'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'deepl',
    name: 'DeepL',
    category: 'writing',
    categoryLabel: 'Writing',
    emoji: '🌍',
    tagline: 'The most accurate AI translator available',
    description: 'More accurate than Google Translate — the best AI translation tool available.',
    longDescription: 'DeepL Translator consistently outperforms other translation tools in accuracy and natural phrasing. Supports 30+ languages with a context-aware AI engine. The free version translates up to 5,000 characters at once and 5 documents/month.',
    url: 'https://deepl.com',
    tags: ['translation', 'AI translator', 'language', 'multilingual'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'writing',
    categoryLabel: 'Writing',
    emoji: '📓',
    tagline: 'All-in-one workspace for notes and docs',
    description: 'All-in-one workspace for notes, docs, wikis, and project management — free forever.',
    longDescription: 'Notion combines notes, documents, wikis, databases, and project boards in one tool. Millions of individuals, startups, and teams use it to organize everything from personal notes to company knowledge bases. Free plan is generous and unlimited for individuals.',
    url: 'https://notion.so',
    tags: ['notes', 'productivity', 'docs', 'wiki', 'project management', 'workspace'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'vscode',
    name: 'VS Code',
    category: 'dev-tools',
    categoryLabel: 'Dev Tools',
    emoji: '💻',
    tagline: "The world's most popular code editor",
    description: "The world's most popular free code editor with extensions for everything.",
    longDescription: 'Visual Studio Code is a free, open-source code editor from Microsoft used by over 73% of developers worldwide. Supports every language, has thousands of extensions, built-in Git, debugging, terminal, and IntelliSense. The undisputed king of code editors.',
    url: 'https://code.visualstudio.com',
    tags: ['code editor', 'IDE', 'developer tool', 'VS Code', 'programming'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'codepen',
    name: 'CodePen',
    category: 'dev-tools',
    categoryLabel: 'Dev Tools',
    emoji: '🖊️',
    tagline: 'Live HTML/CSS/JS playground in the browser',
    description: 'Online HTML/CSS/JS playground. Share, fork, and demo code live in the browser.',
    longDescription: "CodePen is the most popular front-end playground and community. Write HTML, CSS, and JavaScript and see live results instantly. Share your \"Pens\" publicly, fork others' work, and discover thousands of UI components and animations.",
    url: 'https://codepen.io',
    tags: ['HTML', 'CSS', 'JavaScript', 'playground', 'frontend', 'code demo'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'dev-tools',
    categoryLabel: 'Dev Tools',
    emoji: '🐙',
    tagline: 'Host code and collaborate with Git',
    description: 'Host code, collaborate on projects, and manage version control for free.',
    longDescription: 'GitHub is the world\'s largest code hosting platform with over 100 million developers. Free plan includes unlimited public and private repositories, GitHub Actions CI/CD, GitHub Pages static hosting, and collaboration tools for teams.',
    url: 'https://github.com',
    tags: ['version control', 'Git', 'code hosting', 'open source', 'CI/CD'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'postman',
    name: 'Postman',
    category: 'dev-tools',
    categoryLabel: 'Dev Tools',
    emoji: '📮',
    tagline: 'Test and debug APIs visually',
    description: "Test and debug APIs visually. Every developer's go-to tool for API work.",
    longDescription: 'Postman is the world\'s most popular API testing platform used by 30 million+ developers. Send HTTP requests, inspect responses, create automated test suites, mock APIs, and collaborate with your team — all from a clean visual interface.',
    url: 'https://postman.com',
    tags: ['API testing', 'REST API', 'debugging', 'developer tool', 'backend'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'regex101',
    name: 'Regex101',
    category: 'dev-tools',
    categoryLabel: 'Dev Tools',
    emoji: '🔍',
    tagline: 'Build and test regex with live explanation',
    description: 'Build, test, and debug regular expressions with live explanation and match highlights.',
    longDescription: 'Regex101 is the most powerful online regular expression tester. Paste your regex and test string to see real-time match highlights, a detailed explanation of every part of your pattern, and a match table. Supports PCRE, Python, JavaScript, and more.',
    url: 'https://regex101.com',
    tags: ['regex', 'regular expressions', 'developer tool', 'string matching', 'debugging'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'jsonformatter',
    name: 'JSON Formatter',
    category: 'dev-tools',
    categoryLabel: 'Dev Tools',
    emoji: '📋',
    tagline: 'Format and validate JSON instantly',
    description: 'Paste ugly JSON and get a clean, readable, collapsible tree instantly.',
    longDescription: 'JSON Formatter & Validator instantly formats, validates, and beautifies JSON data. Paste your raw JSON and get a color-coded, collapsible tree view. Also validates your JSON and highlights syntax errors. Used daily by developers working with APIs.',
    url: 'https://jsonformatter.org',
    tags: ['JSON', 'formatter', 'validator', 'developer tool', 'API'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'crontab-guru',
    name: 'Crontab Guru',
    category: 'dev-tools',
    categoryLabel: 'Dev Tools',
    emoji: '⏰',
    tagline: 'Translate cron expressions into plain English',
    description: 'Translate cron schedule expressions into plain English. Every DevOps person loves this.',
    longDescription: 'Crontab Guru is the quickest way to understand or create a cron schedule expression. Type any cron expression and instantly see a human-readable description of when it runs, along with the next scheduled times. Bookmarked by every developer who works with cron jobs.',
    url: 'https://crontab.guru',
    tags: ['cron', 'scheduler', 'DevOps', 'Linux', 'automation'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'unsplash',
    name: 'Unsplash',
    category: 'images',
    categoryLabel: 'Images',
    emoji: '📸',
    tagline: 'Millions of free high-res photos',
    description: 'Millions of stunning free high-resolution photos with no attribution required.',
    longDescription: 'Unsplash has over 3 million free high-resolution photos contributed by photographers worldwide. All photos are free to use commercially — no attribution required. Perfect for blog posts, websites, presentations, and marketing materials.',
    url: 'https://unsplash.com',
    tags: ['free photos', 'stock photos', 'high resolution', 'commercial use', 'photography'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'pexels',
    name: 'Pexels',
    category: 'images',
    categoryLabel: 'Images',
    emoji: '🖼️',
    tagline: 'Free stock photos and videos',
    description: 'Free stock photos and videos — great alternative to Unsplash with video support.',
    longDescription: 'Pexels provides high-quality free stock photos and videos. All content is free for commercial use without attribution. With over 3.2 million free stock photos and 100k+ videos, it\'s the most complete free media library available.',
    url: 'https://pexels.com',
    tags: ['free photos', 'free videos', 'stock media', 'commercial use'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'tinypng',
    name: 'TinyPNG',
    category: 'images',
    categoryLabel: 'Images',
    emoji: '🗜️',
    tagline: 'Compress images up to 80% without quality loss',
    description: 'Compress PNG, JPEG and WebP files up to 80% without visible quality loss.',
    longDescription: 'TinyPNG uses smart lossy compression to reduce PNG, JPEG, and WebP file sizes by 60–80% without noticeable quality loss. Critical for website performance — large uncompressed images are the #1 cause of slow websites. Free for 20 images/month.',
    url: 'https://tinypng.com',
    tags: ['image compression', 'optimize images', 'PNG', 'JPEG', 'performance', 'web speed'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'remove-bg',
    name: 'Remove.bg',
    category: 'images',
    categoryLabel: 'Images',
    emoji: '✂️',
    tagline: 'Remove image backgrounds in seconds',
    description: 'Remove any image background in seconds using AI — free for small images.',
    longDescription: 'Remove.bg uses AI to automatically remove backgrounds from photos in seconds with remarkable accuracy. Works on people, products, animals, and complex objects. The free version provides low-resolution results, which is perfect for web use.',
    url: 'https://remove.bg',
    tags: ['background removal', 'AI image editing', 'product photos', 'photo editing'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'squoosh',
    name: 'Squoosh',
    category: 'images',
    categoryLabel: 'Images',
    emoji: '🔧',
    tagline: "Google's powerful image compression tool",
    description: "Google's image compression tool. Convert, resize, and optimize images in the browser.",
    longDescription: 'Squoosh is an open-source image compression web app from Google. Compare different compression formats (WebP, AVIF, MozJPEG, etc.) side-by-side and see the exact quality vs file size tradeoff. Runs entirely in your browser — no server upload needed.',
    url: 'https://squoosh.app',
    tags: ['image optimization', 'WebP', 'AVIF', 'compression', 'Google', 'performance'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'favicon-io',
    name: 'Favicon.io',
    category: 'images',
    categoryLabel: 'Images',
    emoji: '🔖',
    tagline: 'Generate a favicon in seconds',
    description: 'Generate a favicon from text, image, or emoji in seconds — free.',
    longDescription: 'Favicon.io is the fastest way to generate favicons for your website. Create from text initials, upload an image, or use an emoji. Generates all required sizes (16x16, 32x32, 180x180, 192x192, 512x512) and provides ready-to-use HTML code.',
    url: 'https://favicon.io',
    tags: ['favicon', 'website icon', 'browser icon', 'web development'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    category: 'ai',
    categoryLabel: 'AI Tools',
    emoji: '🤖',
    tagline: "The world's most-used AI assistant",
    description: "The world's most-used AI assistant for writing, coding, research, and analysis.",
    longDescription: 'ChatGPT by OpenAI is the most popular AI chatbot with over 200 million weekly users. Use it to write content, debug code, summarize documents, brainstorm ideas, answer questions, and automate repetitive tasks. GPT-4o is free with limits.',
    url: 'https://chat.openai.com',
    tags: ['AI assistant', 'ChatGPT', 'OpenAI', 'writing', 'coding', 'research', 'automation'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'claude',
    name: 'Claude',
    category: 'ai',
    categoryLabel: 'AI Tools',
    emoji: '🧠',
    tagline: 'Best AI for long documents and complex tasks',
    description: "Anthropic's AI — outstanding for long documents, analysis, and safe reasoning.",
    longDescription: 'Claude by Anthropic excels at tasks requiring careful reasoning, analysis of long documents, and nuanced writing. Its 200K token context window means it can read an entire book or codebase. Preferred by developers and researchers for complex tasks.',
    url: 'https://claude.ai',
    tags: ['AI assistant', 'Claude', 'Anthropic', 'document analysis', 'coding', 'reasoning'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    category: 'ai',
    categoryLabel: 'AI Tools',
    emoji: '🔎',
    tagline: 'AI-powered search with cited answers',
    description: 'AI search that gives direct cited answers instead of links — real-time web access.',
    longDescription: 'Perplexity AI is a conversational search engine that searches the web in real time and gives direct, cited answers instead of a list of links. Ask any question and get a comprehensive answer with sources you can verify. Perfect for research.',
    url: 'https://perplexity.ai',
    tags: ['AI search', 'research', 'web search', 'real-time information', 'citations'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'gamma',
    name: 'Gamma',
    category: 'ai',
    categoryLabel: 'AI Tools',
    emoji: '📊',
    tagline: 'Turn a prompt into a beautiful presentation',
    description: 'Turn a text prompt into a beautiful presentation or document in seconds with AI.',
    longDescription: 'Gamma generates professional presentations, documents, and web pages from a text prompt in under 30 seconds. It handles layout, design, and content structure automatically. Far faster than PowerPoint or Google Slides for creating first drafts.',
    url: 'https://gamma.app',
    tags: ['AI presentations', 'slides', 'document generation', 'productivity', 'design'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'v0',
    name: 'v0 by Vercel',
    category: 'ai',
    categoryLabel: 'AI Tools',
    emoji: '⚡',
    tagline: 'Generate React UI components from text',
    description: 'Generate full React/Next.js UI components from a text description instantly.',
    longDescription: 'v0 by Vercel generates production-ready React UI components from natural language descriptions. Describe the UI you want and get clean, copy-paste-ready code using Tailwind CSS and shadcn/ui. Revolutionary for developers who want to prototype fast.',
    url: 'https://v0.dev',
    tags: ['AI code generation', 'React', 'UI components', 'Next.js', 'Tailwind', 'Vercel'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'runway',
    name: 'Runway ML',
    category: 'ai',
    categoryLabel: 'AI Tools',
    emoji: '🎬',
    tagline: 'AI video generation and editing',
    description: 'AI video generation, editing, and background removal from video.',
    longDescription: 'Runway ML is the leading AI creative platform for video generation and editing. Generate videos from text or images, remove backgrounds from video in real time, apply visual effects, and use AI to edit footage. Used by professional filmmakers and content creators.',
    url: 'https://runwayml.com',
    tags: ['AI video', 'video generation', 'video editing', 'background removal', 'creative AI'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'google-search-console',
    name: 'Google Search Console',
    category: 'seo',
    categoryLabel: 'SEO',
    emoji: '📈',
    tagline: 'Monitor your Google rankings for free',
    description: 'Monitor your Google rankings, crawl errors, and search performance — completely free.',
    longDescription: 'Google Search Console is a free tool every website owner must use. Track exactly which search queries bring traffic, identify crawl errors, submit your sitemap, monitor Core Web Vitals, and see how Google sees your pages. Essential for any SEO strategy.',
    url: 'https://search.google.com/search-console',
    tags: ['SEO', 'Google rankings', 'search traffic', 'crawl errors', 'sitemap', 'Core Web Vitals'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'ahrefs-webmaster',
    name: 'Ahrefs Webmaster Tools',
    category: 'seo',
    categoryLabel: 'SEO',
    emoji: '🔗',
    tagline: 'Free backlink checker and site audit',
    description: 'Free backlink analysis and site audit tool from the world\'s top SEO platform.',
    longDescription: "Ahrefs Webmaster Tools gives you free access to Ahrefs' powerful backlink checker and site audit tool for your own websites. See all backlinks pointing to your site, find broken links, identify SEO issues, and track keyword rankings.",
    url: 'https://ahrefs.com/webmaster-tools',
    tags: ['SEO', 'backlinks', 'site audit', 'keyword rankings', 'link building'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'pagespeed-insights',
    name: 'PageSpeed Insights',
    category: 'seo',
    categoryLabel: 'SEO',
    emoji: '⚡',
    tagline: 'Test your site speed and Core Web Vitals',
    description: "Google's tool to test site speed and Core Web Vitals — the score that affects rankings.",
    longDescription: 'PageSpeed Insights measures your website\'s performance and Core Web Vitals (LCP, FID, CLS) — the actual metrics Google uses as a ranking factor. Get a score out of 100 and specific actionable recommendations for improving both mobile and desktop performance.',
    url: 'https://pagespeed.web.dev',
    tags: ['page speed', 'Core Web Vitals', 'performance', 'Google ranking', 'LCP', 'CLS'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'ubersuggest',
    name: 'Ubersuggest',
    category: 'seo',
    categoryLabel: 'SEO',
    emoji: '🔑',
    tagline: 'Free keyword research tool by Neil Patel',
    description: 'Free keyword research, SEO audit, and competitor analysis by Neil Patel.',
    longDescription: 'Ubersuggest by Neil Patel offers free keyword research, content ideas, backlink data, and site audits. Enter any domain or keyword to see search volume, competition, CPC, and long-tail keyword suggestions. Free plan gives 3 daily searches.',
    url: 'https://neilpatel.com/ubersuggest',
    tags: ['keyword research', 'SEO audit', 'competitor analysis', 'content ideas', 'Neil Patel'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'gtmetrix',
    name: 'GTmetrix',
    category: 'seo',
    categoryLabel: 'SEO',
    emoji: '📊',
    tagline: 'Detailed website speed test and waterfall',
    description: 'Detailed website speed test with waterfall chart, grades, and optimization tips.',
    longDescription: 'GTmetrix analyzes your page load speed and shows a detailed waterfall chart of every request, load times by resource, and performance grades. Helps you identify exactly what is slowing your site down. Test from multiple locations and monitor over time.',
    url: 'https://gtmetrix.com',
    tags: ['website speed', 'performance testing', 'waterfall chart', 'optimization', 'load time'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'smallpdf',
    name: 'Smallpdf',
    category: 'convert',
    categoryLabel: 'Convert',
    emoji: '📄',
    tagline: '21 free PDF tools in one place',
    description: 'Convert, compress, merge, split, and edit PDFs — 21 tools in one free site.',
    longDescription: 'Smallpdf offers 21 online PDF tools: compress, merge, split, convert to/from Word/Excel/PPT/JPG, sign, edit, and protect PDFs. Handles tasks that normally require expensive desktop software. Free plan allows 2 tasks/hour.',
    url: 'https://smallpdf.com',
    tags: ['PDF', 'convert PDF', 'compress PDF', 'merge PDF', 'Word to PDF', 'PDF editor'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'ilovepdf',
    name: 'ILovePDF',
    category: 'convert',
    categoryLabel: 'Convert',
    emoji: '❤️',
    tagline: 'Merge, split, rotate, and convert PDFs',
    description: 'Merge, split, rotate, compress, and convert PDFs completely free.',
    longDescription: 'ILovePDF provides free, fast, and easy PDF tools. Merge multiple PDFs, split a PDF by pages, compress file size, convert to/from Word, Excel, and PowerPoint, rotate pages, add watermarks, and unlock password-protected PDFs.',
    url: 'https://ilovepdf.com',
    tags: ['PDF tools', 'merge PDF', 'PDF converter', 'compress PDF', 'split PDF'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'cloudconvert',
    name: 'CloudConvert',
    category: 'convert',
    categoryLabel: 'Convert',
    emoji: '☁️',
    tagline: 'Convert between 200+ file formats',
    description: 'Convert between 200+ formats: video, audio, image, document, spreadsheet, and more.',
    longDescription: 'CloudConvert supports conversion between over 200 file formats including video (MP4, MOV, AVI), audio (MP3, WAV, FLAC), images (JPG, PNG, WebP, SVG), documents (PDF, DOCX, XLSX), and archives (ZIP, RAR). 25 free conversions/day.',
    url: 'https://cloudconvert.com',
    tags: ['file converter', 'video conversion', 'audio conversion', 'format conversion', 'document'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'convertio',
    name: 'Convertio',
    category: 'convert',
    categoryLabel: 'Convert',
    emoji: '🔄',
    tagline: 'Drag, drop, and convert any file',
    description: 'Quick file converter — drag, drop, and convert any file. No software needed.',
    longDescription: 'Convertio supports over 300 file formats and is one of the simplest converters to use. Drag and drop your file, choose the output format, and download the result. Works with documents, images, videos, audio, ebooks, and archives.',
    url: 'https://convertio.co',
    tags: ['file converter', 'online converter', 'format conversion', 'drag and drop'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    category: 'convert',
    categoryLabel: 'Convert',
    emoji: '📱',
    tagline: 'Create custom QR codes for anything',
    description: 'Create custom QR codes for URLs, WiFi passwords, vCards, and more — free.',
    longDescription: 'QR Code Generator creates custom QR codes for websites, WiFi credentials, contact cards (vCard), plain text, email addresses, SMS, and phone numbers. Customize colors, add a logo, and download as PNG, SVG, or EPS. Free for static QR codes.',
    url: 'https://qr-code-generator.com',
    tags: ['QR code', 'QR generator', 'business card', 'WiFi QR', 'marketing'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'loom',
    name: 'Loom',
    category: 'video',
    categoryLabel: 'Video',
    emoji: '🎥',
    tagline: 'Record and share screen videos instantly',
    description: 'Record screen + camera instantly and share as a link. Free up to 5 min per video.',
    longDescription: 'Loom is the fastest way to record and share screen recordings. Record your screen, camera, or both, and instantly get a shareable link. No uploads, no waiting — the link is ready the moment you stop recording. Used by 25 million+ people for async communication.',
    url: 'https://loom.com',
    tags: ['screen recording', 'video messaging', 'async communication', 'tutorials', 'demos'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'capcut',
    name: 'CapCut',
    category: 'video',
    categoryLabel: 'Video',
    emoji: '✂️',
    tagline: 'Free video editor for short-form content',
    description: 'Free, powerful video editor for short-form content, reels, and social media.',
    longDescription: 'CapCut is a free all-in-one video editor used by 300 million+ creators. Edit videos with auto-captions, background removal, transitions, effects, text overlays, and music. Available as a web app and mobile app. Perfect for Instagram Reels, TikTok, and YouTube Shorts.',
    url: 'https://capcut.com',
    tags: ['video editing', 'social media video', 'Reels', 'TikTok', 'content creation', 'auto captions'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'descript',
    name: 'Descript',
    category: 'video',
    categoryLabel: 'Video',
    emoji: '🎙️',
    tagline: 'Edit video by editing the transcript',
    description: 'Edit video and podcasts by editing the text transcript — remove filler words automatically.',
    longDescription: 'Descript transcribes your video or audio and lets you edit it like a text document. Delete a word from the transcript and it deletes that part of the video. Remove all "um"s and "uh"s in one click. Revolutionary for podcasters and video creators.',
    url: 'https://descript.com',
    tags: ['video editing', 'podcast editing', 'transcription', 'filler word removal', 'audio editing'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'obs-studio',
    name: 'OBS Studio',
    category: 'video',
    categoryLabel: 'Video',
    emoji: '📡',
    tagline: 'Free open-source screen recording and streaming',
    description: 'Free open-source screen recording and live streaming — the industry standard.',
    longDescription: 'OBS Studio (Open Broadcaster Software) is the most powerful free screen recording and live streaming software available. Used by professional streamers, educators, and content creators worldwide. Records in high quality, streams to YouTube/Twitch/Facebook, and supports custom scenes and overlays.',
    url: 'https://obsproject.com',
    tags: ['screen recording', 'live streaming', 'OBS', 'open source', 'YouTube', 'Twitch'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    category: 'utilities',
    categoryLabel: 'Utilities',
    emoji: '📊',
    tagline: 'Track website visitors and behavior for free',
    description: 'Track website visitors, traffic sources, and user behavior — completely free.',
    longDescription: 'Google Analytics 4 is the most widely used web analytics platform, used by over 28 million websites. Track pageviews, user sessions, traffic sources, conversion goals, e-commerce revenue, and user behavior flows. Free with no usage limits.',
    url: 'https://analytics.google.com',
    tags: ['web analytics', 'website traffic', 'user behavior', 'conversion tracking', 'Google'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'utilities',
    categoryLabel: 'Utilities',
    emoji: '📅',
    tagline: 'Let clients book meetings without email back-and-forth',
    description: 'Let clients and partners book meetings without the email back-and-forth.',
    longDescription: 'Calendly eliminates the back-and-forth of scheduling meetings. Share your link, people pick a time that works for both, and the meeting is automatically added to both calendars with a confirmation. Free plan supports 1 event type and unlimited meetings.',
    url: 'https://calendly.com',
    tags: ['scheduling', 'meeting booking', 'calendar', 'appointment', 'productivity'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'whimsical',
    name: 'Whimsical',
    category: 'utilities',
    categoryLabel: 'Utilities',
    emoji: '🗺️',
    tagline: 'Wireframes, flowcharts, and mind maps',
    description: 'Create wireframes, flowcharts, mind maps, and sticky notes — fast and beautiful.',
    longDescription: 'Whimsical is a visual workspace for wireframes, flowcharts, mind maps, and sticky note boards. It\'s significantly faster and more polished than Miro for quick visual thinking. Perfect for planning website structures, user flows, and brainstorming sessions.',
    url: 'https://whimsical.com',
    tags: ['wireframes', 'flowcharts', 'mind maps', 'planning', 'UX design', 'brainstorming'],
    isFree: true,
    hasPaid: true,
  },
  {
    id: 'virustotal',
    name: 'VirusTotal',
    category: 'utilities',
    categoryLabel: 'Utilities',
    emoji: '🛡️',
    tagline: 'Scan files and URLs against 70+ antivirus engines',
    description: 'Scan any file or URL against 70+ antivirus engines instantly — free.',
    longDescription: 'VirusTotal (owned by Google) lets you upload any file or enter any URL to scan it against 70+ antivirus engines simultaneously. Find out in seconds if something is malicious. Essential for safely opening unknown email attachments or visiting suspicious links.',
    url: 'https://virustotal.com',
    tags: ['security', 'antivirus', 'malware scanner', 'file scan', 'URL scan', 'cybersecurity'],
    isFree: true,
    hasPaid: false,
  },
  {
    id: 'haveibeenpwned',
    name: 'Have I Been Pwned',
    category: 'utilities',
    categoryLabel: 'Utilities',
    emoji: '🔐',
    tagline: 'Check if your email was leaked in a data breach',
    description: 'Check if your email or phone was leaked in a data breach. Everyone should use this.',
    longDescription: 'Have I Been Pwned (HIBP) lets you check if your email address or phone number has been exposed in any known data breach. With 12 billion+ compromised accounts in the database, enter your email and see exactly which breaches exposed your data.',
    url: 'https://haveibeenpwned.com',
    tags: ['data breach', 'security', 'password safety', 'email security', 'privacy', 'cybersecurity'],
    isFree: true,
    hasPaid: false,
  },
];

export const categories = [
  { id: 'all', label: 'All Tools', emoji: '⚡', count: 50 },
  { id: 'design', label: 'Design', emoji: '🎨', count: 6 },
  { id: 'writing', label: 'Writing', emoji: '✍️', count: 6 },
  { id: 'dev-tools', label: 'Dev Tools', emoji: '💻', count: 7 },
  { id: 'images', label: 'Images', emoji: '🖼️', count: 6 },
  { id: 'ai', label: 'AI Tools', emoji: '🤖', count: 6 },
  { id: 'seo', label: 'SEO', emoji: '📈', count: 5 },
  { id: 'convert', label: 'Convert', emoji: '🔄', count: 5 },
  { id: 'video', label: 'Video', emoji: '🎬', count: 4 },
  { id: 'utilities', label: 'Utilities', emoji: '🛠️', count: 5 },
];
